config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resource :wizard do
    get :step1
    get :step2
    get :step3
    get :step4

    post :validate_step
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, format: { with: /@/ }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address_1, presence: true
  validates :zipcode, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController
  before_action :load_user_wizard, except: %i(validate_step)

  def validate_step
    current_step = params[:current_step]

    @user_wizard = wizard_user_for_step(current_step)
    @user_wizard.user.attributes = user_wizard_params
    session[:user_attributes] = @user_wizard.user.attributes

    if @user_wizard.valid?
      next_step = wizard_user_next_step(current_step)
      create and return unless next_step

      redirect_to action: next_step
    else
      render current_step
    end
  end

  def create
    if @user_wizard.user.save
      session[:user_attributes] = nil
      redirect_to root_path, notice: 'User succesfully created!'
    else
      redirect_to({ action: Wizard::User::STEPS.first }, alert: 'There were a problem when creating the user.')
    end
  end

  private

  def load_user_wizard
    @user_wizard = wizard_user_for_step(action_name)
  end

  def wizard_user_next_step(step)
    Wizard::User::STEPS[Wizard::User::STEPS.index(step) + 1]
  end

  def wizard_user_for_step(step)
    raise InvalidStep unless step.in?(Wizard::User::STEPS)

    "Wizard::User::#{step.camelize}".constantize.new(session[:user_attributes])
  end

  def user_wizard_params
    params.require(:user_wizard).permit(:email, :first_name, :last_name, :address_1, :zipcode, :city, :country, :phone_number)
  end

  class InvalidStep < StandardError; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/wizards_helper.rb
module WizardsHelper
end

app/views/home/index.html.erb
<h2>User wizard</h2>

<%= link_to "Create a user", step1_wizard_path, class: 'btn btn-success' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StepForm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/wizards/step1.html.erb
<ol class="breadcrumb">
  <li class='active'>Step 1</li>
  <li>Step 2</li>
  <li>Step 3</li>
  <li>Step 4</li>
</ol>

<%= form_for @user_wizard, as: :user_wizard, url: validate_step_wizard_path do |f| %>
   <% if @user_wizard.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user_wizard.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @user_wizard.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag :current_step, 'step1' %>
   <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>

  <%= f.submit 'Continue' %>
<% end %>

app/views/wizards/step2.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Step 1", step1_wizard_path %></li>
  <li class="active">Step 2</li>
  <li>Step 3</li>
  <li>Step 4</li>
</ol>

<%= form_for @user_wizard, as: :user_wizard, url: validate_step_wizard_path do |f| %>
  <% if @user_wizard.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user_wizard.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @user_wizard.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag :current_step, 'step2' %>
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  

  <%= f.submit 'Continue' %>
<% end %>

app/views/wizards/step3.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Step 1", step1_wizard_path %></li>
  <li><%= link_to "Step 2", step2_wizard_path %></li>
  <li class="active">Step 3</li>
  <li>Step 4</li>
</ol>

<%= form_for @user_wizard, as: :user_wizard, url: validate_step_wizard_path do |f| %>
  <% if @user_wizard.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user_wizard.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @user_wizard.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag :current_step, 'step3' %>
  <p>
    <%= f.label :address_1 %><br>
    <%= f.text_field :address_1 %>
  </p>

  
   <p>
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode %>
  </p>

   <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>

   <p>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </p>
 

  <%= f.submit 'Continue' %>
<% end %>

app/views/wizards/step4.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Step 1", step1_wizard_path %></li>
  <li><%= link_to "Step 2", step2_wizard_path %></li>
  <li><%= link_to "Step 3", step3_wizard_path %></li>
  <li class="active">Step 4</li>
</ol>

<%= form_for @user_wizard, as: :user_wizard, url: validate_step_wizard_path do |f| %>
  <% if @user_wizard.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user_wizard.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @user_wizard.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag :current_step, 'step4' %>
   <p>
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </p>

  <%= f.submit 'Finish' %>
<% end %>